### ISSUE TITLE
Add gender, hh type, insurance, earnings to summary files

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/ACS#107]
Adding these for stanton commons tables. @maggiesu0725 

ACS_summary_geo_source_tr_vars
ACS_summary_geo.sas

**Comment by lhendey** [comment]
@maggiesu0725 @rpitingolo if this issue is still in progress can you add variables for table b11016? 

A variable for each row basically:

Number of 2 person family households...etc.
Number 1 person nonfamily households....

And Number family households with 4+ people
Number of nonfamily households with 4+ people 

B11016 |   |   | HOUSEHOLD TYPE BY HOUSEHOLD SIZE
-- | -- | -- | --
B11016 |   |   | Universe:  Households
B11016 | 1 | B11016_001 | Total:
B11016 | 2 | B11016_002 | Family households:
B11016 | 3 | B11016_003 | 2-person household
B11016 | 4 | B11016_004 | 3-person household
B11016 | 5 | B11016_005 | 4-person household
B11016 | 6 | B11016_006 | 5-person household
B11016 | 7 | B11016_007 | 6-person household
B11016 | 8 | B11016_008 | 7-or-more person household
B11016 | 9 | B11016_009 | Nonfamily households:
B11016 | 10 | B11016_010 | 1-person household
B11016 | 11 | B11016_011 | 2-person household
B11016 | 12 | B11016_012 | 3-person household
B11016 | 13 | B11016_013 | 4-person household
B11016 | 14 | B11016_014 | 5-person household
B11016 | 15 | B11016_015 | 6-person household
B11016 | 16 | B11016_016 | 7-or-more person household

**Comment by lhendey** [comment]
@rpitingolo - can we close this issue?

**Comment by rpitingolo** [comment]
@lhendey yes
