### ISSUE TITLE
Add children under 5 in poverty to ACS summary files

### ISSUE THREAD

**Issue by chedman** [NeighborhoodInfoDC/ACS#14]

**Comment by ptatian** [comment]
@chedman @rpitingolo There were some coding errors in the original commit that Carl made earlier. Some of the new var names were too long; there were unneeded quotes in the revisions= parameter value. Also, you need to make sure the new MOE variables are added to the ACS_summary_geo.sas, otherwise they won't end up in the output data sets. 

The program should have been given a test run before issuing the pull request and before merging the pull back to Master.  This would have revealed these errors.

**Comment by chedman** [comment]
@ptatian @rpitingolo Yes, sorry for not catching those earlier. I believe I reviewed the wrong output file on my initial pass. Rob and I have address those issues and the corrected error-free program has been uploaded. We were able to produce the updated ACS summary files without error, but let me know if you notice any issues. 

Thanks,
Carl
